# network architecture
# encoder related
encoder: transformer
encoder_conf:
    input_layer: "conv2d2"
    num_blocks: 12
    linear_units: 2048
    dropout_rate: 0.1
    output_size: 256  # dimension of attention
    attention_heads: 4
    attention_dropout_rate: 0.0

#freeze_param: ["frontend.upstream"] 

frontend: default_s3prl
frontend_conf:
  frontend_conf_s3prl:
      upstream: hubert_large_ll60k  # Note: If the upstream is changed, please change the input_size in the preencoder  
  download_dir: ./hub
  multilayer_feature: True
  align_method: elevator  
  alpha: 0.0

apply_moe_on: fbank

# decoder related
# decoder related
decoder: transformer
decoder_conf:
    input_layer: "embed"
    num_blocks: 6
    linear_units: 2048
    dropout_rate: 0.1

# hybrid CTC/attention
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

# minibatch related
batch_type: folded
batch_size: 32

# optimization related
optim: adam
accum_grad: 2
grad_clip: 5
patience: 15
max_epoch: 100
optim_conf:
    lr: 1.0
scheduler: noamlr
scheduler_conf:
    warmup_steps: 4000

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2

# others:
best_model_criterion:
-  - valid
   - acc
   - max
keep_nbest_models: 10

init: xavier_uniform # Our empirical studies shows that this initialization
                     # is very important to low-resource ASR training
