# model_type can be chosen from "sa"(SA-EEND) or "eda"(EEND-EDA).
# For the details about SA-EEND and EEND-EDA, refer to the following papers:
# SA-EEND: https://arxiv.org/pdf/1909.06247.pdf
# EEND-EDA: https://arxiv.org/pdf/2005.09921.pdf, https://arxiv.org/pdf/2106.10654.pdf
model_conf:
    model_type: eda 

# network architecture
# encoder related
encoder: transformer
encoder_conf:
    input_layer: "linear"
    num_blocks: 2
    linear_units: 512
    dropout_rate: 0.1
    output_size: 256  # dimension of attention
    attention_heads: 4
    attention_dropout_rate: 0.0

# attractor related
attractor: rnn
attractor_conf:
    unit: 256 # same as encoder output size
    layer: 1
    dropout: 0.1

# decoder related
#decoder: linear

# chunk-based training
iterator_type: chunk
chunk_length: 200000
num_cache_chunks: 64

# minibatch related
batch_type: folded
batch_size: 16

# optimization related
optim: adam
accum_grad: 2
grad_clip: 5
patience: 3
max_epoch: 100
optim_conf:
    lr: 0.01
scheduler: noamlr
scheduler_conf:
    warmup_steps: 1000

# others:
best_model_criterion:
-  - valid
   - acc
   - max
keep_nbest_models: 3

init: xavier_uniform
