\n******************************\n
vae_jan_12_modified_130
asr_adv_asradv
/srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/dump
/srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/vae_jan_12_modified_130/30_50_50_single_optim/exp
********\n Important setting data direcotry  *********** \n
\n data directory : /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data  \n
\n****************************\n
2023-01-12T14:48:21 (vae_asr_skip_data_lm.sh:306:main) ./vae_asr_skip_data_lm.sh --skip_data_prep false --skip_train false --skip_eval false --lang en --ngpu 1 --nj 32 --use_xvector true --inference_nj 32 --nbpe 5000 --max_wav_duration 30 --speed_perturb_factors 0.9 1.0 1.1 --audio_format flac.ark --feats_type raw --use_lm false --asr_tag conformer_lr2e-3_warmup15k_amp_nondeterministic --asr_config /home/rgupta/dev/espnet/egs2/librispeech_100/asr1/conf/train_asr_vae.yaml --inference_config /home/rgupta/dev/espnet/egs2/librispeech_100/asr1/conf/decode_asr.yaml --train_set train_clean_100 --valid_set dev --test_sets test_clean test_other dev_clean dev_other --lm_train_text /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100/text --bpe_train_text /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100/text
2023-01-12T14:48:21 (vae_asr_skip_data_lm.sh:704:main) Stage 5: Generate token_list from /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100/text using BPE
stage 3: x-vector extraction
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//utils/copy_data_dir.sh: copied data from /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp to /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp_mfcc_16k
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//utils/copy_data_dir.sh: file feats.scp exists in dest /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp_mfcc_16k but not in src /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp.  Moving it to
 ... /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp_mfcc_16k/.backup/feats.scp
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//utils/copy_data_dir.sh: file vad.scp exists in dest /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp_mfcc_16k but not in src /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp.  Moving it to
 ... /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp_mfcc_16k/.backup/vad.scp
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//utils/copy_data_dir.sh: file utt2dur exists in dest /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp_mfcc_16k but not in src /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp.  Moving it to
 ... /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp_mfcc_16k/.backup/utt2dur
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//utils/copy_data_dir.sh: file utt2num_frames exists in dest /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp_mfcc_16k but not in src /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp.  Moving it to
 ... /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp_mfcc_16k/.backup/utt2num_frames
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//utils/copy_data_dir.sh: file frame_shift exists in dest /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp_mfcc_16k but not in src /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp.  Moving it to
 ... /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp_mfcc_16k/.backup/frame_shift
utils/validate_data_dir.sh: Successfully validated data-directory /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp_mfcc_16k
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//steps/make_mfcc.sh --write-utt2num-frames true --mfcc-config /home/rgupta/dev/espnet/egs2/librispeech_100/asr1//conf/mfcc.conf --nj 32 --cmd run.pl /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp_mfcc_16k /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/vae_jan_12_modified_130/30_50_50_single_optim/exp/make_mfcc_16k /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/mfccdir
utils/validate_data_dir.sh: Successfully validated data-directory /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp_mfcc_16k
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//steps/make_mfcc.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//steps/make_mfcc.sh: Succeeded creating MFCC features for train_clean_100_sp_mfcc_16k
fix_data_dir.sh: kept all 85617 utterances.
fix_data_dir.sh: old files are kept in /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp_mfcc_16k/.backup
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//steps/compute_vad_decision.sh --nj 32 --cmd run.pl /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp_mfcc_16k /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/vae_jan_12_modified_130/30_50_50_single_optim/exp/make_vad /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/mfcc
Created VAD output for train_clean_100_sp_mfcc_16k
fix_data_dir.sh: kept all 85617 utterances.
fix_data_dir.sh: old files are kept in /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp_mfcc_16k/.backup
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//utils/copy_data_dir.sh: copied data from /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/dev_clean to /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/dev_clean_mfcc_16k
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//utils/copy_data_dir.sh: file feats.scp exists in dest /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/dev_clean_mfcc_16k but not in src /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/dev_clean.  Moving it to
 ... /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/dev_clean_mfcc_16k/.backup/feats.scp
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//utils/copy_data_dir.sh: file vad.scp exists in dest /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/dev_clean_mfcc_16k but not in src /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/dev_clean.  Moving it to
 ... /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/dev_clean_mfcc_16k/.backup/vad.scp
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//utils/copy_data_dir.sh: file utt2dur exists in dest /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/dev_clean_mfcc_16k but not in src /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/dev_clean.  Moving it to
 ... /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/dev_clean_mfcc_16k/.backup/utt2dur
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//utils/copy_data_dir.sh: file utt2num_frames exists in dest /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/dev_clean_mfcc_16k but not in src /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/dev_clean.  Moving it to
 ... /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/dev_clean_mfcc_16k/.backup/utt2num_frames
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//utils/copy_data_dir.sh: file frame_shift exists in dest /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/dev_clean_mfcc_16k but not in src /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/dev_clean.  Moving it to
 ... /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/dev_clean_mfcc_16k/.backup/frame_shift
utils/validate_data_dir.sh: Successfully validated data-directory /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/dev_clean_mfcc_16k
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//steps/make_mfcc.sh --write-utt2num-frames true --mfcc-config /home/rgupta/dev/espnet/egs2/librispeech_100/asr1//conf/mfcc.conf --nj 32 --cmd run.pl /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/dev_clean_mfcc_16k /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/vae_jan_12_modified_130/30_50_50_single_optim/exp/make_mfcc_16k /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/mfccdir
utils/validate_data_dir.sh: Successfully validated data-directory /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/dev_clean_mfcc_16k
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//steps/make_mfcc.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//steps/make_mfcc.sh: Succeeded creating MFCC features for dev_clean_mfcc_16k
fix_data_dir.sh: kept all 2703 utterances.
fix_data_dir.sh: old files are kept in /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/dev_clean_mfcc_16k/.backup
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//steps/compute_vad_decision.sh --nj 32 --cmd run.pl /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/dev_clean_mfcc_16k /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/vae_jan_12_modified_130/30_50_50_single_optim/exp/make_vad /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/mfcc
Created VAD output for dev_clean_mfcc_16k
fix_data_dir.sh: kept all 2703 utterances.
fix_data_dir.sh: old files are kept in /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/dev_clean_mfcc_16k/.backup
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//utils/copy_data_dir.sh: copied data from /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/test_clean to /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/test_clean_mfcc_16k
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//utils/copy_data_dir.sh: file feats.scp exists in dest /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/test_clean_mfcc_16k but not in src /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/test_clean.  Moving it to
 ... /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/test_clean_mfcc_16k/.backup/feats.scp
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//utils/copy_data_dir.sh: file vad.scp exists in dest /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/test_clean_mfcc_16k but not in src /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/test_clean.  Moving it to
 ... /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/test_clean_mfcc_16k/.backup/vad.scp
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//utils/copy_data_dir.sh: file utt2dur exists in dest /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/test_clean_mfcc_16k but not in src /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/test_clean.  Moving it to
 ... /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/test_clean_mfcc_16k/.backup/utt2dur
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//utils/copy_data_dir.sh: file utt2num_frames exists in dest /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/test_clean_mfcc_16k but not in src /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/test_clean.  Moving it to
 ... /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/test_clean_mfcc_16k/.backup/utt2num_frames
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//utils/copy_data_dir.sh: file frame_shift exists in dest /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/test_clean_mfcc_16k but not in src /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/test_clean.  Moving it to
 ... /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/test_clean_mfcc_16k/.backup/frame_shift
utils/validate_data_dir.sh: Successfully validated data-directory /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/test_clean_mfcc_16k
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//steps/make_mfcc.sh --write-utt2num-frames true --mfcc-config /home/rgupta/dev/espnet/egs2/librispeech_100/asr1//conf/mfcc.conf --nj 32 --cmd run.pl /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/test_clean_mfcc_16k /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/vae_jan_12_modified_130/30_50_50_single_optim/exp/make_mfcc_16k /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/mfccdir
utils/validate_data_dir.sh: Successfully validated data-directory /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/test_clean_mfcc_16k
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//steps/make_mfcc.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//steps/make_mfcc.sh: Succeeded creating MFCC features for test_clean_mfcc_16k
fix_data_dir.sh: kept all 2620 utterances.
fix_data_dir.sh: old files are kept in /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/test_clean_mfcc_16k/.backup
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//steps/compute_vad_decision.sh --nj 32 --cmd run.pl /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/test_clean_mfcc_16k /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/vae_jan_12_modified_130/30_50_50_single_optim/exp/make_vad /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/mfcc
Created VAD output for test_clean_mfcc_16k
fix_data_dir.sh: kept all 2620 utterances.
fix_data_dir.sh: old files are kept in /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/test_clean_mfcc_16k/.backup
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//../../../tools/kaldi/egs/sre08/v1/sid/nnet3/xvector/extract_xvectors.sh --cmd run.pl --mem 4G --nj 32 /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/dump/nnet/ /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp_mfcc_16k /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/dump/nnet//xvectors_train_clean_100_sp
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//../../../tools/kaldi/egs/sre08/v1/sid/nnet3/xvector/extract_xvectors.sh: using /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/dump/nnet//extract.config to extract xvectors
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//../../../tools/kaldi/egs/sre08/v1/sid/nnet3/xvector/extract_xvectors.sh: extracting xvectors for /srv/storage/talc2@talc-data2.nancy/multispeech/calcul/users/rgupta/fresh_libri_100/data_with_speed_version_xvector/original_data/train_clean_100_sp_mfcc_16k
/home/rgupta/dev/espnet/egs2/librispeech_100/asr1//../../../tools/kaldi/egs/sre08/v1/sid/nnet3/xvector/extract_xvectors.sh: extracting xvectors from nnet
