#    If "attractor" is "None" or not specified, SA-EEND will be used. 
#    Else if "attractor" is not "None" EEND-EDA will be used.
#    For the details about SA-EEND and EEND-EDA, refer to the following papers:
#    SA-EEND: https://arxiv.org/pdf/1909.06247.pdf
#    EEND-EDA: https://arxiv.org/pdf/2005.09921.pdf, https://arxiv.org/pdf/2106.10654.pdf


# network architecture
# encoder related
encoder: conformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 512
    num_blocks: 4
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: linear
    normalize_before: true
    macaron_style: true
    pos_enc_layer_type: "rel_pos"
    selfattention_layer_type: "rel_selfattn"
    activation_type: "swish"
    use_cnn_module:  true
    cnn_module_kernel: 31

# attractor related
attractor: rnn
attractor_conf:
    unit: 256 # same as encoder output size
    layer: 1
    dropout: 0.1
    attractor_grad: False

# decoder related
#decoder: linear

# chunk-based training
iterator_type: chunk
chunk_length: 20000
num_cache_chunks: 64

# minibatch related
batch_type: folded
batch_size: 64

# optimization related
optim: adam
accum_grad: 1
grad_clip: 5
max_epoch: 100
optim_conf:
    lr: 0.02
scheduler: noamlr
scheduler_conf:
    warmup_steps: 50000

# others:
best_model_criterion:
-  - valid
   - acc
   - max
keep_nbest_models: 3

specaug: specaug
specaug_conf:
    apply_time_warp: false
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2