#    If "attractor" is "None" or not specified, SA-EEND will be used. 
#    Else if "attractor" is not "None" EEND-EDA will be used.
#    For the details about SA-EEND and EEND-EDA, refer to the following papers:
#    SA-EEND: https://arxiv.org/pdf/1909.06247.pdf
#    EEND-EDA: https://arxiv.org/pdf/2005.09921.pdf, https://arxiv.org/pdf/2106.10654.pdf


# network architecture
# encoder related
encoder: transformer
encoder_conf:
    input_layer: "linear"
    num_blocks: 4
    linear_units: 512
    dropout_rate: 0.1
    output_size: 256  # dimension of attention
    attention_heads: 4
    attention_dropout_rate: 0.1

# attractor related
attractor: rnn
attractor_conf:
    unit: 256 # same as encoder output size
    layer: 1
    dropout: 0.1
    attractor_grad: True

# decoder related
#decoder: linear

# chunk-based training
#iterator_type: chunk
#chunk_length: 20000
#num_cache_chunks: 64

# minibatch related
#batch_type: folded
#batch_size: 64

# optimization related
optim: adam
#accum_grad: 2
grad_clip: 5
max_epoch: 250
optim_conf:
    lr: 0.002
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 30000

# others:
best_model_criterion:
-  - valid
   - acc
   - max
keep_nbest_models: 10

batch_type: numel
batch_bins: 15000000
accum_grad: 6
#max_epoch: 100
patience: none
# The initialization method for model parameters
init: xavier_uniform

specaug: specaug
specaug_conf:
    apply_time_warp: false
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
#    apply_time_mask: false
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2